# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: build
    displayName: 'master-branch-build'

    #build jobs
    jobs:
      - job: build
        pool:
          name: 'Scientia-Pool'
          
        variables:
          buildConfiguration: 'Release'
        steps:
        - task: NuGetToolInstaller@1
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: 'ScientiaWebAPI/ScientiaWebAPI/ScientiaWebAPI.csproj'
            feedsToUse: 'select' 
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: 'ScientiaWebAPI/ScientiaWebAPI/ScientiaWebAPI.csproj'
            arguments: '--configuration $(BuildConfiguration)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: 'ScientiaWebAPI/ScientiaTest/ScientiaTest.csproj'
            arguments: '--configuration $(buildConfiguration)'
            testRunTitle: 'Test-CI- CD'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: false
            projects: 'ScientiaWebAPI/ScientiaTest/ScientiaTest.csproj'
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'


